name: Default Pipeline for Ascentware HR Management

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: js-app/package-lock.json

      - name: Install Dependencies
        working-directory: js-app
        run: npm i

      - name: Run ESLint (Code Quality Check)
        working-directory: js-app
        run: npm run lint

      - name: Run Prettier (Formatting Check)
        working-directory: js-app
        run: npm run format:check

      - name: Build React App
        working-directory: js-app
        run: npm run build

      # - name: Upload Build Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: react-build
      #     path: js-app/dist
